version: '3'

services:
  app:
    build: .
    command: >
      bash -c "python manage.py collectstatic --noinput --clear
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    container_name: product_management
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"