services:
  app:
    build: .
    command: >
      bash -c "cd zebrands
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    container_name: zebrands_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"